#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
AI Music Composer - Music Player
Script to play MIDI files generated by the AI Music Composer
"""

import sys
import os
import logging
from audio_processor import AudioProcessor
from music21 import converter

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s',
    handlers=[
        logging.StreamHandler()
    ]
)

logger = logging.getLogger(__name__)

def play_midi_file(midi_file_path):
    """Play a MIDI file using the AudioProcessor"""
    if not os.path.exists(midi_file_path):
        print(f"Error: MIDI file '{midi_file_path}' not found.")
        return False
    
    try:
        # Create an AudioProcessor instance
        audio_proc = AudioProcessor()
        
        # Load the MIDI file into a music21 score
        print(f"Loading MIDI file: {midi_file_path}")
        score = converter.parse(midi_file_path)
        
        # Play the score
        print("Playing music... (Press Ctrl+C to stop)")
        success = audio_proc.play_score(score)
        
        if success:
            print("Playback started successfully.")
            
            # Wait for playback to finish or user to interrupt
            try:
                while audio_proc.is_playback_active():
                    import time
                    time.sleep(0.5)
                print("Playback completed.")
            except KeyboardInterrupt:
                print("\nPlayback stopped by user.")
                audio_proc.stop_playback()
        else:
            print("Failed to start playback.")
        
        return success
    
    except Exception as e:
        logger.error(f"Error playing MIDI file: {e}")
        return False

def main():
    """Main function to play a MIDI file"""
    try:
        # Get the MIDI file path from arguments or use default
        if len(sys.argv) > 1:
            midi_file_path = sys.argv[1]
        else:
            # Check if we have generated files
            if os.path.exists("ai_composition.mid"):
                midi_file_path = "ai_composition.mid"
            elif os.path.exists("output.mid"):
                midi_file_path = "output.mid"
            else:
                print("No MIDI file specified and no default files found.")
                print("Usage: python play_music.py [midi_file_path]")
                return
        
        print(f"=== AI Music Composer - Music Player ===")
        play_midi_file(midi_file_path)
        
    except Exception as e:
        logger.error(f"Application error: {e}")
        import traceback
        traceback.print_exc()
        sys.exit(1)

if __name__ == "__main__":
    main()